### ISSUE TITLE
Feature Request: Make dots at start of game visible to players

### ISSUE THREAD

**Issue by JamesOwers** [RyanrDavies/curvytron-client#5]
Currently the canvas is blank at the start of the game. Players need to know where other players are in order to position themselves (and not immediately crash)

**Comment by RyanrDavies** [comment]
Yep, at the moment the client only returns the trails, it should return the heads of the players as well. Probably easiest to just draw them onto a copy of the trails canvas before returning rather than keeping a separate head canvas -- would get difficult keeping it correctly up to date.
